"""update

Revision ID: 415decc0b97a
Revises: 8b903b1ca15c
Create Date: 2016-06-26 18:25:20.657036

"""

# revision identifiers, used by Alembic.
revision = '415decc0b97a'
down_revision = '8b903b1ca15c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
