"""add title

Revision ID: 8b903b1ca15c
Revises: a94570842c90
Create Date: 2016-06-26 15:55:04.479719

"""

# revision identifiers, used by Alembic.
revision = '8b903b1ca15c'
down_revision = 'a94570842c90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
