"""gavater

Revision ID: a94570842c90
Revises: None
Create Date: 2016-06-26 01:45:22.550627

"""

# revision identifiers, used by Alembic.
revision = 'a94570842c90'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
